# Generated by Django 5.2.3 on 2025-10-16 08:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import backend.manager
import utils.model_translation


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "hero_title",
                    models.JSONField(default=dict, help_text="Main hero title"),
                ),
                (
                    "hero_subtitle",
                    models.JSONField(default=dict, help_text="Hero subtitle/tagline"),
                ),
                (
                    "hero_description",
                    models.JSONField(default=dict, help_text="Hero description text"),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Hero banner image",
                        null=True,
                        upload_to="about_us/hero/",
                    ),
                ),
                (
                    "hero_video_url",
                    models.URLField(
                        blank=True, help_text="Optional hero video URL", null=True
                    ),
                ),
                (
                    "company_name",
                    models.JSONField(default=dict, help_text="Company name"),
                ),
                (
                    "company_tagline",
                    models.JSONField(default=dict, help_text="Company tagline/slogan"),
                ),
                (
                    "company_description",
                    models.JSONField(
                        default=dict, help_text="Main company description"
                    ),
                ),
                (
                    "founded_year",
                    models.IntegerField(
                        blank=True, help_text="Year founded", null=True
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us/logos/"
                    ),
                ),
                (
                    "mission_statement",
                    models.JSONField(
                        default=dict, help_text="Company mission statement"
                    ),
                ),
                (
                    "vision_statement",
                    models.JSONField(
                        default=dict, help_text="Company vision statement"
                    ),
                ),
                (
                    "core_values",
                    models.JSONField(
                        default=list,
                        help_text="List of core values (each item should be a dict with 'title' and 'description')",
                    ),
                ),
                (
                    "our_story_title",
                    models.JSONField(default=dict, help_text="Story section title"),
                ),
                (
                    "our_story_content",
                    models.JSONField(default=dict, help_text="Company story/history"),
                ),
                (
                    "our_story_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us/story/"
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        blank=True, help_text="Years in business", null=True
                    ),
                ),
                (
                    "projects_completed",
                    models.IntegerField(
                        blank=True, help_text="Number of completed projects", null=True
                    ),
                ),
                (
                    "satisfied_clients",
                    models.IntegerField(
                        blank=True, help_text="Number of clients", null=True
                    ),
                ),
                (
                    "team_members",
                    models.IntegerField(
                        blank=True, help_text="Number of team members", null=True
                    ),
                ),
                (
                    "cta_title",
                    models.JSONField(default=dict, help_text="Call-to-action title"),
                ),
                (
                    "cta_description",
                    models.JSONField(
                        default=dict, help_text="Call-to-action description"
                    ),
                ),
                (
                    "cta_button_text",
                    models.JSONField(default=dict, help_text="CTA button text"),
                ),
                (
                    "cta_button_link",
                    models.URLField(blank=True, help_text="CTA link URL", null=True),
                ),
                (
                    "meta_title",
                    models.JSONField(default=dict, help_text="Page meta title for SEO"),
                ),
                (
                    "meta_description",
                    models.JSONField(
                        default=dict, help_text="Page meta description for SEO"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this page is currently active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Us Page",
                "verbose_name_plural": "About Us Pages",
                "db_table": "about_us_page",
            },
            bases=(models.Model, utils.model_translation.AutoTranslateMixin),
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.CreateModel(
            name="AboutUsSection",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Content"),
                            ("text_image", "Text with Image"),
                            ("image_text", "Image with Text"),
                            ("features", "Feature List"),
                            ("statistics", "Statistics"),
                            ("quote", "Quote/Testimonial"),
                            ("video", "Video"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("title", models.JSONField(default=dict, help_text="Section title")),
                (
                    "subtitle",
                    models.JSONField(default=dict, help_text="Section subtitle"),
                ),
                ("content", models.JSONField(default=dict, help_text="Main content")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="about_us/sections/"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Video URL", null=True),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data (e.g., feature list, stats)",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show on website?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Us Section",
                "verbose_name_plural": "About Us Sections",
                "db_table": "about_us_section",
                "ordering": ["display_order"],
            },
            bases=(models.Model, utils.model_translation.AutoTranslateMixin),
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyAchievement",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "title",
                    models.JSONField(default=dict, help_text="Achievement title"),
                ),
                (
                    "description",
                    models.JSONField(default=dict, help_text="Achievement description"),
                ),
                (
                    "awarded_by",
                    models.JSONField(
                        default=dict, help_text="Organization/entity that awarded"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, help_text="Year received", null=True
                    ),
                ),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        help_text="Certificate/award image",
                        null=True,
                        upload_to="about_us/achievements/",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show on website?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Achievement",
                "verbose_name_plural": "Company Achievements",
                "db_table": "company_achievement",
                "ordering": ["display_order", "-year"],
            },
            bases=(models.Model, utils.model_translation.AutoTranslateMixin),
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyTimeline",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("year", models.IntegerField(help_text="Year of milestone")),
                ("title", models.JSONField(default=dict, help_text="Milestone title")),
                (
                    "description",
                    models.JSONField(default=dict, help_text="Milestone description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Timeline image",
                        null=True,
                        upload_to="about_us/timeline/",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show on website?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Timeline",
                "verbose_name_plural": "Company Timeline",
                "db_table": "company_timeline",
                "ordering": ["-year", "display_order"],
            },
            bases=(models.Model, utils.model_translation.AutoTranslateMixin),
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("full_name", models.CharField(help_text="Full name", max_length=255)),
                (
                    "job_title",
                    models.JSONField(default=dict, help_text="Job title/position"),
                ),
                (
                    "bio",
                    models.JSONField(default=dict, help_text="Biography/description"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone", max_length=20, null=True
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn profile", null=True
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter profile", null=True),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Profile photo",
                        null=True,
                        upload_to="about_us/team/",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "is_leadership",
                    models.BooleanField(
                        default=False,
                        help_text="Is this person part of leadership team?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show on website?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "db_table": "team_member",
                "ordering": ["display_order", "full_name"],
            },
            bases=(models.Model, utils.model_translation.AutoTranslateMixin),
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
    ]
