# Generated by Django 5.2.3 on 2025-08-26 17:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.JSONField(default=dict, help_text="Content of the message"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.JSONField(
                default=dict, help_text="Name of the person sending the message"
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.JSONField(default=dict, help_text="Subject of the message"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.JSONField(
                default=dict, help_text="The answer to the question"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.JSONField(
                default=dict, help_text="The frequently asked question"
            ),
        ),
    ]
