# Generated by Django 5.2.3 on 2025-10-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_aboutuspage_aboutussection_companyachievement_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutuspage",
            old_name="team_members",
            new_name="team_members_count",
        ),
    ]
