# Generated by Django 5.2.3 on 2025-10-17 02:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import backend.manager
import utils.model_translation


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_rename_team_members_aboutuspage_team_members_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastNews",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "title",
                    models.JSONField(
                        default=dict, help_text="Title of the broadcast news/interview"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the title",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "channel_name",
                    models.JSONField(
                        default=dict, help_text="Name of the news channel"
                    ),
                ),
                (
                    "interviewer_name",
                    models.JSONField(
                        blank=True, default=dict, help_text="Name of the interviewer"
                    ),
                ),
                (
                    "interviewee_name",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Name of the person being interviewed",
                    ),
                ),
                (
                    "interview_date",
                    models.DateField(help_text="Date when the interview was conducted"),
                ),
                (
                    "broadcast_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the interview was/will be broadcast",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        default=dict, help_text="Brief description of the interview"
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for the broadcast news",
                        null=True,
                        upload_to="broadcast_news/thumbnails/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the video of the interview (YouTube, Vimeo, etc.)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded video file of the interview",
                        null=True,
                        upload_to="broadcast_news/videos/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Published", "Published")],
                        default="Draft",
                        help_text="Publication status",
                        max_length=10,
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, help_text="Number of views"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="Duration of the interview (e.g., '30 minutes')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "meta_title",
                    models.JSONField(
                        blank=True, default=dict, help_text="SEO meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.JSONField(
                        blank=True, default=dict, help_text="SEO meta description"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured to display prominently",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which the broadcast news should be displayed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast News",
                "verbose_name_plural": "Broadcast News",
                "db_table": "broadcast_news",
                "ordering": ["-broadcast_date", "display_order", "-created_at"],
            },
            bases=(models.Model, utils.model_translation.AutoTranslateMixin),
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.CreateModel(
            name="BroadcastNewsDetail",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "speaker",
                    models.JSONField(
                        default=dict,
                        help_text="Name of the speaker (Interviewer/Interviewee)",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict, help_text="Content/dialogue of this line"
                    ),
                ),
                (
                    "timestamp",
                    models.CharField(
                        blank=True,
                        help_text="Timestamp in the video (e.g., '00:05:30')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of this line in the interview"
                    ),
                ),
                (
                    "broadcast_news",
                    models.ForeignKey(
                        help_text="Related broadcast news",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="cms.broadcastnews",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast News Detail",
                "verbose_name_plural": "Broadcast News Details",
                "db_table": "broadcast_news_detail",
                "ordering": ["broadcast_news", "order"],
            },
            bases=(models.Model, utils.model_translation.AutoTranslateMixin),
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
    ]
