# Generated by Django 5.2.3 on 2025-10-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_broadcastnews_broadcastnewsdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutuspage",
            name="company_tagline",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="core_values",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="cta_button_link",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="cta_button_text",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="cta_description",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="cta_title",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="hero_description",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="hero_video_url",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="our_story_image",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="projects_completed",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="satisfied_clients",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="team_members_count",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="years_of_experience",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="email",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="twitter_url",
        ),
        migrations.DeleteModel(
            name="AboutUsSection",
        ),
    ]
