# Generated by Django 5.2.3 on 2025-11-08 12:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_change_teammember_full_name_to_jsonfield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["display_order", "created_at"],
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.AddField(
            model_name="broadcastnews",
            name="article_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the original article or press mention",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="broadcastnews",
            name="publication_name",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Name of the publication/media outlet",
            ),
        ),
    ]
