# Generated by Django 5.2.3 on 2025-06-30 17:10

from django.db import migrations

import backend.manager


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="activitylog",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="company",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="conteact",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="content",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="contenttype",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="country",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="course",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="document",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="documentaccess",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="language",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="lead",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="module",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="productcategory",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="professional",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="region",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="role",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="usagelog",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
    ]
