# Generated by Django 5.2.3 on 2025-07-01 16:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import backend.manager


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_activitylog_managers_alter_company_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry_type",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="content",
            name="body",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="content",
            name="meta_tag",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="meta_title",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="title",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="contenttype",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contenttype",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="country",
            name="notes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="professional",
            name="profile_summary",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="professional",
            name="specializations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.JSONField(default=dict)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("job_title", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.lead"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", backend.manager.SoftDeletionManager()),
            ],
        ),
        migrations.DeleteModel(
            name="conteact",
        ),
    ]
