# Generated by Django 5.2.3 on 2025-07-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_activitylog_details_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
        migrations.AlterModelTable(
            name="region",
            table=None,
        ),
    ]
