# Generated by Django 5.2.3 on 2025-07-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_product_table_alter_region_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="content",
            options={"verbose_name": "Content", "verbose_name_plural": "Contents"},
        ),
        migrations.AlterModelOptions(
            name="contenttype",
            options={
                "verbose_name": "Content Type",
                "verbose_name_plural": "Content Types",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterModelOptions(
            name="documentaccess",
            options={
                "verbose_name": "Document Access",
                "verbose_name_plural": "Document Accesses",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "Language", "verbose_name_plural": "Languages"},
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={"verbose_name": "Lead", "verbose_name_plural": "Leads"},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "Module", "verbose_name_plural": "Modules"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="professional",
            options={
                "verbose_name": "Professional",
                "verbose_name_plural": "Professionals",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Region", "verbose_name_plural": "Regions"},
        ),
        migrations.AlterModelOptions(
            name="usagelog",
            options={"verbose_name": "Usage Log", "verbose_name_plural": "Usage Logs"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="language",
            table="language",
        ),
        migrations.AlterModelTable(
            name="region",
            table="region",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
